on:
  push:
    branches:
      - main
env:
  NODE_VERSION: '14.x'   # set this to the node version to use
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, and build
      run: |
        cd frontend
        npm install
        npm run build
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: frontend/dist   # The folder the action should deploy.